# Site settings
title: Jinsung Kim's Page
baseurl: ""
url: "https://jin62304.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Jinsung Kim
  desc: Ph.D. Candidate, NLP & AI Lab., Korea University
  email: jin62304@gmail.com
  selfie: assets/img/profile_jinsung.jpg

# social
social:
  email:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: jin62304
  google_plus:
  google_scholar: https://scholar.google.com/citations?hl=ko&user=au6e9uUAAAAJ
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/jinsung-kim-703195178/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
#paginate_path: "/portfolio/page:num/"
#paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
